### ISSUE TITLE
Compiling cjdns for armhf in qemu docker hangs occasionally

### ISSUE THREAD

**Issue by benhylau** [benhylau/mesh-router-builder#9]
The cjdns compile for armhf in a docker container occasionally hangs. You can see that it's hung by doing `sudo docker stats` in another SSH session to the vagrant box and see that the container `CPU %` has dropped to zero. The run line for the container is as follow:

```
sudo docker run --cpuset-cpus=0 --memory 1G --oom-kill-disable -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static -v $(BUILD_DIR)/docker/build:/tmp/cjdns cjdns-armv7hf
```

I currently have `--memory 1G --oom-kill-disable` and have tried having a 6G vagrant and 3G / 5G docker memory limit, but the issue persists, so I added the oom killer disable. I also added `--cpuset-cpus=0` because of https://github.com/resin-io-projects/armv7hf-debian-qemu/issues/2#issuecomment-248826656. The occasional hangs still occur, most commonly at the cjdns compile step:

>Build Libuv

`strace` of the process shows:

```
vagrant@stretch:~$ strace -p 28449
strace: Process 28449 attached
wait4(-1,
```

Upon killing the container with `sudo docker kill <container-name>` I get:

```
vagrant@stretch:~$ strace -p 28449
strace: Process 28449 attached
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 137}], 0, NULL) = 28450
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=28450, si_uid=0, si_status=137, si_utime=0, si_stime=0} ---
rt_sigreturn({mask=[]})                 = 28450
exit_group(137)                         = ?
+++ exited with 137 +++
```

The current workaround is to `vagrant ssh` in another session, kill the container, and stop the make and then run `make` again.

**Comment by benhylau** [comment]
May be useful to note that `sudo docker info` shows:

```
...

WARNING: No swap limit support
```

 and that is also pointed out in dockerd logs.

**Comment by benhylau** [comment]
Using cjdns `cross-do` instead of docker. This is not needed anymore.

**Comment by jedahan** [comment]
I wonder how `cross-do` does it, but glad that it works. I'm using `ryankurte/docker-rpi-emu` but should probably switch to the resin-io one because those look more up-to-date.

**Comment by benhylau** [comment]
resin.io one looked to be best option for me at the time. cjdns can use cross compile toolchain to compile for many architectures, it wasn't very well documented so I couldn't get it working initially, until eventually I got some help.
